flags: {}
extra-package-dbs: []
packages:
- '.'
- 'imgui'
extra-deps:
- FTGL-2.1
- aeson-0.11.3.0
- base-orphans-0.6
- lambdacube-gl-0.5.2.3
- lambdacube-ir-0.3.0.1
- pqueue-1.3.1.1
- reactive-banana-1.1.0.1
- semigroupoids-5.2
- websockets-0.11.1.0
resolver: lts-8.12
