flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- frpnow-0.18
- gloss-1.10.1.1
- gloss-rendering-1.10.1.1
- netwire-5.0.0
- pqueue-1.3.1.1
- reactive-banana-1.1.0.1
- ref-tf-0.4
- reflex-0.4.0
resolver: lts-6.6
